import React from 'react';
import {
    Zap,
    Truck,
    Package,
    MapPin,
    Clock,
    CheckCircle,
    AlertCircle,
    Plus,
    Search,
    Filter,
    Download,
    Users,
    BarChart,
    X,
    ChevronLeft,
    Moon,
    Sun,
    LayoutDashboard,
    Info,
    BellOff
} from 'lucide-react';

export const Icons = {
    Zap: (props: React.ComponentProps<typeof Zap>) => <Zap size={18} {...props} />,
    Truck: (props: React.ComponentProps<typeof Truck>) => <Truck size={18} {...props} />,
    Package: (props: React.ComponentProps<typeof Package>) => <Package size={18} {...props} />,
    MapPin: (props: React.ComponentProps<typeof MapPin>) => <MapPin size={18} {...props} />,
    Clock: (props: React.ComponentProps<typeof Clock>) => <Clock size={18} {...props} />,
    CheckCircle: (props: React.ComponentProps<typeof CheckCircle>) => <CheckCircle size={18} {...props} />,
    AlertCircle: (props: React.ComponentProps<typeof AlertCircle>) => <AlertCircle size={18} {...props} />,
    Plus: (props: React.ComponentProps<typeof Plus>) => <Plus size={20} {...props} />,
    Search: (props: React.ComponentProps<typeof Search>) => <Search size={18} {...props} />,
    Filter: (props: React.ComponentProps<typeof Filter>) => <Filter size={16} {...props} />,
    Download: (props: React.ComponentProps<typeof Download>) => <Download size={18} {...props} />,
    Users: (props: React.ComponentProps<typeof Users>) => <Users size={18} {...props} />,
    BarChart: (props: React.ComponentProps<typeof BarChart>) => <BarChart size={18} {...props} />,
    X: (props: React.ComponentProps<typeof X>) => <X size={24} {...props} />,
    ChevronLeft: (props: React.ComponentProps<typeof ChevronLeft>) => <ChevronLeft size={24} {...props} />,
    Moon: (props: React.ComponentProps<typeof Moon>) => <Moon size={24} {...props} />,
    Sun: (props: React.ComponentProps<typeof Sun>) => <Sun size={24} {...props} />,
    Dashboard: (props: React.ComponentProps<typeof LayoutDashboard>) => <LayoutDashboard size={24} {...props} />,
    Info: (props: React.ComponentProps<typeof Info>) => <Info size={24} {...props} />,
    BellOff: (props: React.ComponentProps<typeof BellOff>) => <BellOff size={24} {...props} />
};
