export enum ShipmentStatus {
    PENDING = "PENDING",
    RECEIVED = "RECEIVED",
    PACKED = "PACKED",
    DISPATCHED = "DISPATCHED",
    IN_TRANSIT = "IN_TRANSIT",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELIVERED = "DELIVERED",
    RETURNED = "RETURNED",
    DISPUTED = "DISPUTED"
}
